repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: name-tests-test
        args: [--pytest-test-first]
    -   id: check-toml
#-   repo: https://github.com/psf/black-pre-commit-mirror   # Still need to look into this some more before enabling it; skipped for now bc pre-commit doesn't work with conda!
#    rev: 24.8.0
#    hooks:
#    -   id: black
#-   repo: https://github.com/PyCQA/isort
#    rev: 5.13.2
#    hooks:
#    -   id: isort