[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mate-manager"
version = "0.0.1"
authors = [
  { name="Jonas Hartmann", email="jonas.hartmann@ucl.ac.uk" },
  { name="Zimeng Wu", email="zimeng.wu.18@ucl.ac.uk" },
]
description = "Automated feedback microscopy to track moving tissues."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
dependencies = [
  "PLACEHOLDER>=1.20",
  "PLACEHOLDER>=0.16"
]
